sample_rate: 16000
feature_dim: 512
num_layers: 8
layer_dim: 1
max_length: 1e10
min_length: 0

encoder: !new:model.qwen3omni.Qwen3Omni
  source: "Qwen/Qwen3-Omni-30B-A3B-Instruct"
  freeze_encoder: True
  sample_rate: !ref <sample_rate>
  output_hidden_states: False

