sample_rate: 24000
feature_dim: 512
num_layers: 8
layer_dim: 1
max_length: 1000
min_length: 1

encoder: !new:model.qwen3_voice.Qwen3Voice
  source: "Qwen/Qwen3-TTS-Tokenizer-12Hz"
  freeze_encoder: True
  sample_rate: !ref <sample_rate>
  output_hidden_states: False

