sample_rate: 16000
feature_dim: 768
max_length: 160000
min_length: 16000
num_layers: 12
layer_dim: 1

encoder: !new:model.wavjepa.WavJEPA
  ssl_encoder_source: "labhamlet/wavjepa-nat-base"
  freeze_encoder: True
  output_hidden_states: False
  sample_rate: !ref <sample_rate>