sample_rate: 16000
feature_dim: 1024
num_layers: 24
layer_dim: 1
max_length: 1e10

encoder: !new:model.wavlm.WavLM
  ssl_encoder_source: "microsoft/wavlm-base-plus"
  freeze_encoder: True
  output_hidden_states: False
  sample_rate: !ref <sample_rate>