sample_rate: 22050
feature_dim: 512 #512 for speaker embedding, 1024 for gpt_cond_latent
num_layers: 1
layer_dim: 1
max_length: 1e10
min_length: 66150   # 3s at 22050Hz — XTTS needs >=3s reference audio

encoder: !new:model.xtts.XTTS
  model_name: "tts_models/multilingual/multi-dataset/xtts_v2"
  freeze_encoder: True
  sample_rate: !ref <sample_rate>
#  which: "speaker_embedding" or gpt_cond_latent" or "both" (default)
  which: "speaker_embedding"