task: c2_c3
task_type: B

dataset: cross_tasks
train_datasets: ["aphasia", "dementiabank"]
test_datasets: ["torgo", "uaspeech", "mdvr", "ksof"]

data_io_script: training.dataio.prep_category_c2_c3
prepare_data_fn: prepare_category_c2_c3

label_key: label_encoded
skip_prep: False

num_labels: 1
loss: !new:torch.nn.BCEWithLogitsLoss

setting_1:  # train_datasets[0] = 'aphasia' (aug params from T9.yaml)
  split_by_boundary: false
  num_aug_ver: 3
  snr_low: 0
  snr_high: 15
  speed: !new:builtins.list
    - !new:builtins.range
      - 90
      - 110
      - 1
setting_2:  # train_datasets[1] = 'dementiabank' (aug params from T7.yaml)
  split_by_boundary: false
  num_aug_ver: 3
  snr_low: 0
  snr_high: 15
  speed: !new:builtins.list
    - !new:builtins.range
      - 90
      - 110
      - 1
test_setting_1: {split_by_boundary: false}
test_setting_2: {split_by_boundary: false}
test_setting_3: {split_by_boundary: false}
test_setting_4: {split_by_boundary: false}
