task: T12_T17
task_type: B

dataset: uaspeech_ksof
train_dataset: uaspeech
test_dataset: ksof

data_io_script: training.dataio.prep_uaspeech_ksof
prepare_data_fn: prepare_uaspeech_ksof_dysC_intC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

train_split_by_boundary: false
test_split_by_boundary: false

num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
