task: T21_T27
task_type: B

dataset: c19sounds_avfad
train_dataset: c19sounds
test_dataset: avfad


# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
# Path to the file containing the dataset-specific preparation and IO functions
data_io_script: training.dataio.prep_c19sounds_avfad

# Name of the function to call for manifest generation
prepare_data_fn: prepare_c19sounds_avfad_t2_pathC

# Key used in the SpeechBrain batch object for the label
label_key: label_encoded

# Data preparation
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

# Augmentation
# For all data that can be trained, during training with cached repr, will sample from versions
train_split_by_boundary: false
test_split_by_boundary: false

num_aug_ver: 3
snr_low: 0
snr_high: 7
speed: !new:builtins.list
  - !new:builtins.range
    - 95 #start
    - 105 #stop
    - 1 #step