task: T6_T1
task_type: B

dataset: iemocap_edaic
train_dataset: iemocap
test_dataset: edaic

data_io_script: training.dataio.prep_edaic_iemocap
prepare_data_fn: prepare_iemocap_edaic_emoBC_depC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

train_split_by_boundary: false
test_split_by_boundary: true

num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
