# HP Optimizer
# Enable Ray Tune hyperparameter optimization
hpopt_mode: null  # Set to 'ray' to enable, null to use EarlyStopping
continue_exp: False  # Continue previous experiment if available (i.e., environment is the same)
optim_metric: 'loss'
optim_mode: 'min'  # 'min' or 'max' depending on the metric
max_concurrent_trials: 1  # Number of concurrent trials to run
grace_period: 3  # Number of epochs to wait before considering early stopping
limit_warmup: 2  # 4: Number of epochs to ignore for ONLY early stopping
reduction_factor: 2  # Factor by which to reduce trials at each rung
sequential: False  # Set to True to run trials sequentially. Else, runs in parallel.
hp_search_seed: 2025  # Seed for reproducible HP sampling (set to null for random)

# Ray Tune specific configuration
ray_tune_config:
  num_samples: 5  # Number of trial runs
  resources_per_trial:
    cpu: 8   # CPUs per trial
    gpu: 1
gpu_per_brain: 0.25 # if a trial has 1 gpu and 4 brains, each brain get 0.25 gpu

# Define hyperparameter search space
# This is optional - if not provided, defaults will be used
hpopt_config:
  lr_s:
    type: "!tune.loguniform"
    values: [1e-4, 1e-3]

  l2:
    type: "!tune.loguniform"
    values: [0.01, 0.1]

#  dropout:
#    type: "!tune.uniform"
#    values: [0.0, 0.5]

#  l2_ratio:
#    type: "!tune.uniform"
#    values: [0.01, 0.5]