# HP Optimizer
# Enable Ray Tune hyperparameter optimization
continue_exp: False  # Continue previous experiment if available (i.e., environment is the same)
optim_metric: 'loss'
optim_mode: 'min'  # 'min' or 'max' depending on the metric
max_concurrent_trials: 1  # Number of concurrent trials to run
grace_period: 5  # max number of epochs without improvement
limit_warmup: 2  # 4: Number of epochs to ignore for ONLY early stopping
hp_search_seed: 2026  # Seed for reproducible HP sampling (set to null for random)

# Ray Tune specific configuration
ray_tune_config:
  num_samples: 5  # Number of trial runs
  resources_per_trial:
    cpu: 8   # CPUs per trial
    gpu: 0

# Define hyperparameter search space
# This is optional - if not provided, defaults will be used
hpopt_config:
  lr_s:
    type: "!tune.loguniform"
    values: [1e-4, 1e-3]

  l2:
    type: "!tune.loguniform"
    values: [0.01, 0.1]

#  l2_ratio:
#    type: "!tune.uniform"
#    values: [0.01, 0.5]