# HP Optimizer
# Enable Ray Tune hyperparameter optimization
hpopt_mode: null  # Set to 'ray' to enable, null to disable
optim_metric: 'F1'
optim_mode: 'max'  # 'min' or 'max' depending on the metric
max_concurrent_trials: 1  # Number of concurrent trials to run
grace_period: 5  # Number of epochs to wait before considering early stopping
reduction_factor: 2  # Factor by which to reduce trials at each rung
sequential: False  # Set to True to run trials sequentially. Else, runs in parallel.

# Ray Tune specific configuration
ray_tune_config:
  num_samples: 10  # Number of trial runs
  resources_per_trial:
    cpu: 92
    gpu: 4


# Define hyperparameter search space
# This is optional - if not provided, defaults will be used
hpopt_config:
  lr:
    type: "!tune.loguniform"
    values: [1e-5, 1e-3]

  number_of_epochs:
    type: "!tune.randint"
    values: [30, 100]

  l2:
    type: "!tune.loguniform"
    values: [1e-5, 1e-3]