File: config/main.yaml
random_seed: 2025
__set_seed: !!python/object/apply:torch.manual_seed [!ref <random_seed>]

model_name: w2v2_LTP
data_folder: ./data/
#----------------------------------
# Most of the knobs you should change
data_params: !include:tasks/c9s_t1.yaml

encoder_params: !include:encoders/w2v2.yaml
# where to store the cached encoder outputs. Will be overwritten every run.
# Turn this on for B x D only, o.w. too big files!
# Also havent thought about multi-GPU  here.
cache_encoder: False
cache_dir: !ref ./.cache/

probe_params: !include:probes/LTProbe.yaml
  feature_dim: !ref <encoder_params[feature_dim]>
  num_labels: 1
  num_layers: !ref <encoder_params[num_layers]>
  layer_dim: !ref <encoder_params[layer_dim]>

hpopt_params: !include:hpopt.yaml
training_params: !include:training.yaml
#----------------------------------
task: !ref <data_params[task]>
dataset: !ref <data_params[dataset]>
rir_folder: !ref <data_folder>

# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
# Path to the file containing the dataset-specific preparation and IO functions
data_io_script: !ref <data_params[data_io_script]>

# Name of the function to call for manifest generation
prepare_data_fn: !ref <data_params[prepare_data_fn]>

# Name of the function to call for defining the data pipelines
dataio_prep_fn: !ref <data_params[dataio_prep_fn]>

# Key used in the SpeechBrain batch object for the label
label_key: !ref <data_params[label_key]>

# ----------------------------------
# DATA PATHS AND PREPARATION
# ----------------------------------
# Original audio and label file paths
wav_folder: !ref <data_folder>/<dataset>/processed/audio
audio_archive_path: !ref <data_folder>/<dataset>/raw/YOUR_ARCHIVE.zip # change this to your own path
metadata_path: !ref <data_folder>/<dataset>/processed/<dataset>.csv
raw_label_key: !ref <data_params[raw_label_key]>

# Output folder structure
output_folder: !ref ./exps/<task>/<model_name>/brain-logs/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Manifest files created by prepare_data_fn
train_annotation: !ref ./exps/<task>/manifest/train.json
val_annotation: !ref ./exps/<task>/manifest/valid.json
test_annotation: !ref ./exps/<task>/manifest/test.json

# Data preparation
skip_prep: !ref <data_params[skip_prep]>
new_test: !ref <data_params[new_test]> # Set False to use metadata's test split. To be implemented

# Cross Validation
num_fold: !ref <data_params[num_fold]> # works from 2 to num. subjects. To be implemented: 0 -> normal split no CV, -1 -> LOSO

# ----------------------------------
# MODEL DEFINITION
# ----------------------------------
# model hyper-parameters
model: !new:model.probe.Model
  encoder: !ref <encoder_params[encoder]>
  probe: !ref <probe_params[probe]>

# modules (for nested modules)
modules:
  model: !ref <model>

# Additional model-related parameters
max_length: !ref <encoder_params[max_length]> # max length in samples (20s)

# ----------------------------------
# TRAINING AND METRICS
# ----------------------------------
test_only: !ref <training_params[test_only]>  # Set to True to only run evaluation on test set
precision: !ref <training_params[precision]>
eval_precision: !ref <training_params[eval_precision]>
number_of_epochs: !ref <training_params[number_of_epochs]>
batch_size: !ref <training_params[batch_size]>
lr: !ref <training_params[lr]>
l2: !ref <training_params[l2]>
sample_rate: !ref <encoder_params[sample_rate]>

skip_nonfinite_grads: !ref <training_params[skip_nonfinite_grads]>
nonfinite_patience: !ref <training_params[nonfinite_patience]>

# Data loader
num_workers: !ref <training_params[num_workers]>
persistent_workers: !ref <training_params[persistent_workers]>
train_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: False
  num_workers: !ref <num_workers>
  persistent_workers: !ref <persistent_workers>
  shuffle: True

val_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: False
  persistent_workers: !ref <persistent_workers>
  num_workers: !ref <num_workers>

test_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: False
  persistent_workers: !ref <persistent_workers>
  num_workers: !ref <num_workers>

# Logger
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>

# Error/Metric calculation
progressbar: !ref <training_params[progressbar]>
error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats

# Epoch management
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <number_of_epochs>

# Optimizer
opt_class: !name:torch.optim.AdamW
  lr: !ref <lr>
  weight_decay: !ref <l2>


# HP Optimizer
# Enable Ray Tune hyperparameter optimization
hpopt_mode: !ref <hpopt_params[hpopt_mode]>
optim_metric: !ref <hpopt_params[optim_metric]>
optim_mode: !ref <hpopt_params[optim_mode]>
max_concurrent_trials: !ref <hpopt_params[max_concurrent_trials]>
grace_period: !ref <hpopt_params[grace_period]>
reduction_factor: !ref <hpopt_params[reduction_factor]>
sequential: !ref <hpopt_params[sequential]>

# Ray Tune specific configuration
ray_tune_config: !ref <hpopt_params[ray_tune_config]>


# Define hyperparameter search space
# This is optional - if not provided, defaults will be used
hpopt_config: !ref <hpopt_params[hpopt_config]>


# Checkpointing
ckpt_interval_minutes: 15 # save checkpoint every N min
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <save_folder>
recoverables:
  model: !ref <model>
  counter: !ref <epoch_counter>