File: config/sylber.yaml
random_seed: 2025
__set_seed: !!python/object/apply:torch.manual_seed [!ref <random_seed>]

task: c9s_t1
model_name: sylber_LTP

data_folder: ./data/
dataset: c9s_t1
rir_folder: !ref <data_folder>


# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
# Path to the file containing the dataset-specific preparation and IO functions
data_io_script: training.dataio.prep_c9s_t1

# Name of the function to call for manifest generation
prepare_data_fn: prepare_data

# Name of the function to call for defining the data pipelines
dataio_prep_fn: dataio_prep

# Key used in the SpeechBrain batch object for the label
label_key: label_encoded

# ----------------------------------
# DATA PATHS AND PREPARATION
# ----------------------------------
# Original audio and label file paths
wav_folder: !ref <data_folder>/<dataset>/processed/audio
audio_archive_path: !ref <data_folder>/<dataset>/raw/YOUR_ARCHIVE.zip # change this to your own path
metadata_path: !ref <data_folder>/<dataset>/processed/<dataset>.csv
raw_label_key: label

# Output folder structure
output_folder: !ref ./exps/<task>/<model_name>/brain-logs/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Manifest files created by prepare_data_fn
train_annotation: !ref ./exps/<task>/manifest/train.json
val_annotation: !ref ./exps/<task>/manifest/valid.json
test_annotation: !ref ./exps/<task>/manifest/test.json

# Data preparation
skip_prep: True
new_test: False # Set False to use metadata's test split.

# Cross Validation
num_fold: 5 # works from 2 to num. subjects. To be implemented: 0 -> normal split no CV, -1 -> LOSO

# ----------------------------------
# MODEL DEFINITION
# ----------------------------------
# model hyper-parameters

encoder: !new:model.Sylber.Sylber
  freeze_encoder: True
  output_hidden_states: True

feature_dim: 768

t_pool: !new:model.pool.AttentiveTemporalPoolLite
  input_dim: !ref <feature_dim>

l_pool: !new:model.pool.LayerWeightedAvgPool
  num_layers: 9
  layer_dim: 1

probe: !new:model.probe.LayerTemporalProbe
  input_dim: !ref <feature_dim>
  num_labels: !ref <n_classes>
  layer_pooler: !ref <l_pool>
  temp_pooler: !ref <t_pool>

#t_pool: !new:model.pool.AvgTPool
#probe: !new:model.probe.TemporalProbe
#  input_dim: !ref <feature_dim>
#  num_labels: !ref <n_classes>
#  temp_pooler: !ref <t_pool>

model: !new:model.probe.Model
  encoder: !ref <encoder>
  probe: !ref <probe>

# modules (for nested modules)
modules:
  model: !ref <model>

# Additional model-related parameters
#max_length: 320000 # max length in samples (20s)

# ----------------------------------
# TRAINING AND METRICS
# ----------------------------------
number_of_epochs: 20
batch_size: 8
lr: 0.001
l2: 0.0001
n_classes: 1
sample_rate: 16000

# Data loader
train_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: True
  num_workers: 0
  shuffle: True

val_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: True
  num_workers: 0

test_dataloader_options:
  batch_size: !ref <batch_size>
  drop_last: True
  num_workers: 0

# Logger
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>

# Error/Metric calculation
progressbar: True
error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats

# Epoch management
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <number_of_epochs>
#  limit_to_stop: 3
#  limit_warmup: 2
#  direction: !ref <optim_mode>

# Optimizer
opt_class: !name:torch.optim.AdamW
  lr: !ref <lr>
  weight_decay: !ref <l2>


# HP Optimizer
# Enable Ray Tune hyperparameter optimization
hpopt_mode: ray  # Set to 'ray' to enable, null to disable
optim_metric: 'F1'
optim_mode: 'max'  # 'min' or 'max' depending on the metric
max_concurrent_trials: 1  # Number of concurrent trials to run
grace_period: 5  # Number of epochs to wait before considering early stopping
reduction_factor: 2  # Factor by which to reduce trials at each rung

# Ray Tune specific configuration
ray_tune_config:
  num_samples: 10  # Number of trial runs
  resources_per_trial:
    cpu: 12
    gpu: 0



# Define hyperparameter search space
# This is optional - if not provided, defaults will be used
hpopt_config:
  lr:
    type: "!tune.loguniform"
    values: [1e-5, 1e-3]

  number_of_epochs:
    type: "!tune.randint"
    values: [10, 100]

  l2:
    type: "!tune.loguniform"
    values: [1e-5, 1e-3]


# Checkpointing
ckpt_interval_minutes: 15 # save checkpoint every N min
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <save_folder>
recoverables:
  model: !ref <model>
  counter: !ref <epoch_counter>