num_workers: 22 # Change when on HPC, this is for DataLoader
batch_size: 32
persistent_workers: True
progressbar: True
test_only: False
precision: fp32
eval_precision: bf16
skip_nonfinite_grads: True
nonfinite_patience: 10
# Ray will override these during hyperparameter optimization
number_of_epochs: 65
lr: 0.00036236320115884353
l2: 0.0618638412578637
#l2_ratio: 0.00001