num_workers: 8 # 22 Change when on HPC, this is for DataLoader
batch_size: 16
persistent_workers: True
progressbar: True
test_only: False
precision: fp32
eval_precision: fp32
skip_nonfinite_grads: True
nonfinite_patience: 10
grad_accumulation_factor: 1
number_of_epochs: 50
# Ray will override these during and after hyperparameter optimization
lr_s: 1e-4
l2: 0.01