task: pwaC
task_type: B

dataset: aphasia

data_io_script: training.dataio.prep_aphasia
prepare_data_fn: prepare_aphasia_pwaC

label_key: label_encoded
skip_prep: True

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

split_by_boundary: false

num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step