task: T12
task_type: B

dataset: uaspeech

# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
data_io_script: training.dataio.prep_uaspeech
prepare_data_fn: prepare_data

label_key: label_encoded
raw_label_key: label

skip_prep: False

num_fold: 5

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

# Augmentation
num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
