task: T23
task_type: L

dataset: c19sounds

data_io_script: training.dataio.prep_c19sounds
prepare_data_fn: prepare_c19sounds_sympL

label_key: label_encoded
skip_prep: False

num_labels: 12

loss: !new:torch.nn.BCEWithLogitsLoss

num_aug_ver: 1
snr_low: 0
snr_high: 7
speed: !new:builtins.list
  - !new:builtins.range
    - 95 #start
    - 105 #stop
    - 1 #step
