sample_rate: 24000
feature_dim: 1024
num_layers: 1
layer_dim: 1
max_length: null
min_length: 1   # 1s at 24kHz

encoder: !new:model.voicecraft_encoder.VoiceCraftEncoder
  voicecraft_source: "pyp1/VoiceCraft"
  freeze_encoder: True
  sample_rate: !ref <sample_rate>
  hook_layer: 12
