feature_dim: !PLACEHOLDER
num_labels: !PLACEHOLDER
num_layers: !PLACEHOLDER
layer_dim: !PLACEHOLDER
threshold: !PLACEHOLDER
min_chunk_size: !PLACEHOLDER

probe: !new:model.probe.LayerChunkTProbe
  input_dim: !ref <feature_dim>
  num_labels: !ref <num_labels>
  layer_pooler: !new:model.pool.LayerWeightedAvgPool
    num_layers: !ref <num_layers>
    layer_dim: !ref <layer_dim>
  temp_pooler: !new:model.pool.AttentiveTemporalPool
    input_dim: 1152
  threshold: !ref <threshold>
  min_chunk_size: !ref <min_chunk_size>