feature_dim: !PLACEHOLDER
num_labels: !PLACEHOLDER

probe: !new:model.probe.TemporalProbe
  input_dim: !ref <feature_dim>
  num_labels: !ref <num_labels>
  temp_pooler: !new:model.pool.AvgTPool
    input_dim: !ref <feature_dim>