feature_dim: !PLACEHOLDER
num_labels: !PLACEHOLDER

probe: !new:model.probe.XTTSProbe
  input_dim: !ref <feature_dim>
  num_labels: !ref <num_labels>
  temp_pooler: !new:model.pool.AttentiveTemporalPool
#  temp_pooler: !new:model.pool.ASP
    input_dim: !ref <feature_dim>