task: sexC
task_type: B

dataset: c9s

data_io_script: training.dataio.prep_c9s
prepare_data_fn: prepare_c9s_sexC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

num_aug_ver: 1
snr_low: 0
snr_high: 7
speed: !new:builtins.list
  - !new:builtins.range
    - 95 #start
    - 105 #stop
    - 1 #step
