task: mvdr

dataset: mvdr

# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
# Path to the file containing the dataset-specific preparation and IO functions
data_io_script: training.dataio.prep_torgo

# Name of the function to call for manifest generation
prepare_data_fn: prepare_data

# Name of the function to call for defining the data pipelines
dataio_prep_fn: dataio_prep

# Key used in the SpeechBrain batch object for the label
label_key: label_encoded

raw_label_key: label
# Data preparation
skip_prep: False
new_test: False # Set False to use metadata's test split.
# Cross Validation
num_fold: 4 # works from 2 to num. subjects. To be implemented: 0 -> normal split no CV, -1 -> LOSO
num_labels: 1

pos_weight: !new:torch.Tensor # Adjust this based on the imbalance in your dataset
  data: [1.3]

loss: !new:torch.nn.BCEWithLogitsLoss
  pos_weight: !ref <pos_weight>

# Augmentation
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step