task: dysC
task_type: B

dataset: nemours

data_io_script: training.dataio.prep_nemours
prepare_data_fn: prepare_nemours_dysC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
