task: emoBC
task_type: B

dataset: ravdess

# ----------------------------------
# DYNAMIC SCRIPT CONFIGURATION (Generic)
# ----------------------------------
# Path to the file containing the dataset-specific preparation and IO functions
data_io_script: training.dataio.prep_ravdess

# Name of the function to call for manifest generation
prepare_data_fn: prepare_emoBC

# Key used in the SpeechBrain batch object for the label
label_key: label_encoded

# Data preparation
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

# Augmentation
# For all data that can be trained, during training with cached repr, will sample from versions
num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step