task: c4_c3
task_type: B

dataset: cross_tasks
train_datasets: ["c9s", "coswara", "avfad"]
test_datasets: ["torgo", "uaspeech", "mvdr", "ksof"]

data_io_script: training.dataio.prep_category_c3_c4
prepare_data_fn: prepare_category_c4_c3

label_key: label_encoded
skip_prep: False
num_labels: 1
loss: !new:torch.nn.BCEWithLogitsLoss

setting_1: {split_by_boundary: false, num_aug_ver: 3}
setting_2: {split_by_boundary: false, num_aug_ver: 3}
setting_3: {split_by_boundary: false, num_aug_ver: 3}
