task: c2_c1
task_type: B

dataset: cross_tasks
train_datasets: ["aphasia", "dbank"]
test_datasets: ["edaic", "ravdess", "iemocap"]

data_io_script: training.dataio.prep_category_c1_c2
prepare_data_fn: prepare_category_c2_c1

label_key: label_encoded
skip_prep: False
num_labels: 1
loss: !new:torch.nn.BCEWithLogitsLoss

setting_1: {split_by_boundary: false, num_aug_ver: 3}
setting_2: {split_by_boundary: false, num_aug_ver: 3}
