task: intC_parkC
task_type: B

dataset: ksof_mvdr
train_dataset: ksof
test_dataset: mvdr

data_io_script: training.dataio.prep_mvdr_ksof
prepare_data_fn: prepare_ksof_mvdr_intC_parkC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

num_aug_ver: 3
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
