task: parkC_dysC
task_type: B

dataset: mvdr_torgo
train_dataset: mvdr
test_dataset: torgo

data_io_script: training.dataio.prep_mvdr_torgo
prepare_data_fn: prepare_mvdr_torgo_parkC_dysC

label_key: label_encoded
skip_prep: False

num_labels: 1

loss: !new:torch.nn.BCEWithLogitsLoss

num_aug_ver: 5
snr_low: 0
snr_high: 15
speed: !new:builtins.list
  - !new:builtins.range
    - 90 #start
    - 110 #stop
    - 1 #step
